development:

    :address: smtp.gmail.com
    :port: 587
    :user_name: 'alejandra.cernas@tangosource.com'
    :password: 'ale.tangosource'
    :authentication: plain
    :enable_starttls_auto: true
production:
    address: smtp.gmail.com
    port: 587
    user_name: 'alejandra.cernas@tangosource.com'
    password: 'ale.tangosource'
    enable_starttls_auto: true
    authentication: plain
