development:
    :address: smtp.gmail.com
    :port: 587
    :user_name: ''
    :password: ''
    :authentication: plain
    :enable_starttls_auto: true
production:
    address: smtp.gmail.com
    port: 587
    user_name: 'alejandra.cernas@tangosource.com'
    password: 'emerak24.'
    enable_starttls_auto: true
    authentication: plain
